︠0558afdd-6226-481b-930d-36db0f7ea88ai︠
%md
# Projet Euler

Voici quelques problèmes tirés du Projet Euler: https://projecteuler.net. Calculez les réponses aux questions et vérifiez sur le site que vous avez trouvé la solution. Vous pouvez rajouter d'autres problèmes après ceux proposés. **A vous d'écrire vos propres programmes ou de chercher dans Sage les fonctionalités dont vous avez besoin**.
︡7268c998-24cd-493c-aeec-10feb6a0c3a2︡︡{"done":true,"md":"# Projet Euler\n\nVoici quelques problèmes tirés du Projet Euler: https://projecteuler.net. Calculez les réponses aux questions et vérifiez sur le site que vous avez trouvé la solution. Vous pouvez rajouter d'autres problèmes après ceux proposés. **A vous d'écrire vos propres programmes ou de chercher dans Sage les fonctionalités dont vous avez besoin**."}
︠6073c105-316f-4cf5-9c52-1b51b95cc3dci︠
%md
### Problème 1


If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

**Find the sum of all the multiples of 3 or 5 below 1000.**

︡6a3fe1f3-4c71-4f3f-91f2-5d285404eac8︡︡{"done":true,"md":"### Problème 1\n\n\nIf we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.\n\n**Find the sum of all the multiples of 3 or 5 below 1000.**"}
︠eba7e7bd-2457-4be6-9559-449a21d66cf4︠
︠28152434-839f-40d0-a8c2-ff6d76a1fad9︠

︠54490e35-1b1e-49b5-9b4a-071094ec61b4i︠
%md
### Problème 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

︡cecb3239-0eed-4c39-a407-b8774b2de981︡︡{"done":true,"md":"### Problème 2\n\nEach new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:\n\n1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\n\nBy considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."}
︠6a3717c6-57d7-4c09-a7bf-7feb916184f1︠
︠103d314f-0182-4a9e-b9fd-f90bb4e6d4c6︠

︠07804992-eae7-42a6-bd44-2331f2861d14i︠
%md 
### Problème 3

The prime factors of 13195 are 5, 7, 13 and 29.

What is the largest prime factor of the number 600851475143 ?

︡2aaa7f66-9cc9-459b-9cc9-f016ea4daa57︡︡{"done":true,"md":"### Problème 3\n\nThe prime factors of 13195 are 5, 7, 13 and 29.\n\nWhat is the largest prime factor of the number 600851475143 ?"}
︠98712e87-b970-410c-a4ca-5665b29776b6︠

︠0768d34b-3f14-4574-b163-95656d965daf︠

︠e0ff342d-7de9-4d9a-9ebc-825d1b61683ei︠
%md
### Problème 4

A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.

Find the largest palindrome made from the product of two 3-digit numbers.

︡a1070828-d787-4115-b533-1738e0707b46︡︡{"done":true,"md":"### Problème 4\n\nA palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.\n\nFind the largest palindrome made from the product of two 3-digit numbers."}
︠a2a5de14-5ed8-4f73-9086-9732a8531872︠
︠7906aa50-17bd-4bdc-a40a-2d09ee2108fd︠

︠2fcaf775-e9e5-437b-8e45-9fa33cdfe916i︠
%md
### Problème 5

2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.

What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?

︡0e3ddcae-23e8-4241-b0c5-0467ffe21008︡︡{"done":true,"md":"### Problème 5\n\n2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.\n\nWhat is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?"}
︠9b59ffc0-61e2-4fb1-a453-e2acfcd87345︠

︠84f36d04-2943-435e-82b3-40dc39e18ee0︠

︠5da920ca-7125-4284-9e90-82cecc3e16dd︠

︠d8523b50-2e10-4831-9120-8c9464be0e5ei︠
%md
### Problème 6


The sum of the squares of the first ten natural numbers is,
$1^2 + 2^2 + ... + 10^2 = 385$

The square of the sum of the first ten natural numbers is,
$(1 + 2 + ... + 10)^2 = 552 = 3025$

Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is $3025 − 385 = 2640$.

Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.

︡0b19d58d-6db9-4251-b73d-cb1188e8a507︡︡{"done":true,"md":"### Problème 6\n\n\nThe sum of the squares of the first ten natural numbers is,\n$1^2 + 2^2 + ... + 10^2 = 385$\n\nThe square of the sum of the first ten natural numbers is,\n$(1 + 2 + ... + 10)^2 = 552 = 3025$\n\nHence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is $3025 − 385 = 2640$.\n\nFind the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum."}
︠e54ac447-f103-4f54-8eb6-b94e30091af2︠
︠562cf643-c6ed-41ff-87ab-99efbbb36e14︠

︠f57ce8c5-1a3a-4259-993d-d83035b85d08︠

︠5c69fbfa-6cb7-4200-81af-6b3dc03eeba8i︠
%md
### Problème 7

By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.

What is the 10 001st prime number?

︡5c178ce6-db0f-4188-9e5d-26dc148ae471︡︡{"done":true,"md":"### Problème 7\n\nBy listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.\n\nWhat is the 10 001st prime number?"}
︠fa8c535f-8612-44b7-8007-f9e91e7242ab︠
︠fd397bd0-6749-4b0e-85f8-09aa7e575776︠

︠8a9ee123-76c3-4ea9-86ef-069225e80385︠

︠f8dfe6e1-dfbc-46db-ac1e-b6331ce95b6b︠

︠0ff96152-3727-446b-8826-a6fe5f6908e4i︠
%md
### Problème 8

The four adjacent digits in this 1000-digit number that have the greatest product are 9 × 9 × 8 × 9 = 5832. Find the thirteen adjacent digits in this 1000-digit number that have the greatest product. What is the value of this product?
︡de971e4f-29b1-4a82-91b0-5cb757e636a6︡︡{"done":true,"md":"### Problème 8\n\nThe four adjacent digits in this 1000-digit number that have the greatest product are 9 × 9 × 8 × 9 = 5832. Find the thirteen adjacent digits in this 1000-digit number that have the greatest product. What is the value of this product?"}
︠cf4abcde-0c9c-4ccc-abcb-26f44faaf8dcs︠
A = 7316717653133062491922511967442657474235534919493496983520312774506326239578318016984801869478851843858615607891129494954595017379583319528532088055111254069874715852386305071569329096329522744304355766896648950445244523161731856403098711121722383113622298934233803081353362766142828064444866452387493035890729629049156044077239071381051585930796086670172427121883998797908792274921901699720888093776657273330010533678812202354218097512545405947522435258490771167055601360483958644670632441572215539753697817977846174064955149290862569321978468622482839722413756570560574902614079729686524145351004748216637048440319989000889524345065854122758866688116427171479924442928230863465674813919123162824586178664583591245665294765456828489128831426076900422421902267105562632111110937054421750694165896040807198403850962455444362981230987879927244284909188845801561660979191338754992005240636899125607176060588611646710940507754100225698315520005593572972571636269561882670428252483600823257530420752963450
︡5cc65a08-605d-4e98-b92f-7a2413b80e8c︡︡{"done":true}
︠a65ee044-984d-496a-af15-ef6443a0d4f3︠

︠3c6cbcbf-3a02-4f34-ae06-5ef9217423d9︠

︠7f7392fd-7cd7-4afc-ba4d-0f3a6836c547i︠
%md
### Problème 9

A Pythagorean triplet is a set of three natural numbers, $a < b < c$, for which,
$a^2 + b^2 = c^2$

For example, $3^2 + 4^2 = 9 + 16 = 25 = 5^2$.

There exists exactly one Pythagorean triplet for which $a + b + c = 1000$.
Find the product abc.

︡8177298d-0885-45a7-8cc3-73bd426980a3︡︡{"done":true,"md":"### Problème 9\n\nA Pythagorean triplet is a set of three natural numbers, $a < b < c$, for which,\n$a^2 + b^2 = c^2$\n\nFor example, $3^2 + 4^2 = 9 + 16 = 25 = 5^2$.\n\nThere exists exactly one Pythagorean triplet for which $a + b + c = 1000$.\nFind the product abc."}
︠55a58593-73cf-4bd7-b54a-f0880e13118c︠
︠0775a0ac-d752-4cbf-8045-523651fdbd9f︠

︠8b3a7379-2ebc-4aed-964c-3531c7669f16i︠
%md
### Problème 10

The sum of the primes below 10 is $2 + 3 + 5 + 7 = 17$.

Find the sum of all the primes below two million.

︡cfaa0641-8ee9-4880-b577-3f59513ade50︡︡{"done":true,"md":"### Problème 10\n\nThe sum of the primes below 10 is $2 + 3 + 5 + 7 = 17$.\n\nFind the sum of all the primes below two million."}
︠841e9dc4-172a-4ac9-9efd-4a9553124caf︠
︠8e66f4da-465a-422e-b2d1-ead78b376843︠









